name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle  # Installiere Gradle

      - name: Create Gradle Wrapper
        run: |
          gradle wrapper  # Erstelle den Gradle Wrapper

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew  # Ã„ndere die Berechtigungen der `gradlew`-Datei

      - name: Build with Gradle
        run: ./gradlew build  # Baue das Projekt

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p public
          cp -r build/distributions/* public
          cd public
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
